
python run_ner_crf.py \
--task_name  'cner' \
--model_type  'bert' \
--model_name_or_path  '/root/models/chinese/bert/pytorch/bert-base-chinese' \
--do_train  \
--do_eval  \
--do_predict  \
--do_lower_case  \
--data_dir  '/root/A/违法主体识别/train_data' \
--train_max_seq_length  200 \
--eval_max_seq_length  200 \
--per_gpu_train_batch_size  8 \
--per_gpu_eval_batch_size  8 \
--learning_rate  2e-5 \
--num_train_epochs  10 \
--logging_steps  300 \
--save_steps  300 \
--output_dir  './outputs' \
--overwrite_output_dir  \
--seed  42 \
--predict_all_checkpoints  \
--log_name  'bert_1'